book_index:
    pattern:  /
    defaults: { _controller: UedayoHabookBundle:Default:index }
book_show:
    pattern:  /{id}/show
    defaults: { _controller: UedayoHabookBundle:Default:show }
book_new:
    pattern: /new
    defaults: { _controller: UedayoHabookBundle:Default:new }
book_delete:
    pattern: /{id}/delete
    defaults: { _controller: UedayoHabookBundle:Default:delete }
book_edit:
    pattern: /{id}/edit
    defaults: { _controller: UedayoHabookBundle:Default:edit }