parameters:
#    uedayo_habook.example.class: Uedayo\HabookBundle\Example

services:
#    uedayo_habook.example:
#        class: %uedayo_habook.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
